In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("matches.csv")
df.to_csv("./matches.csv", index=False)

In [2]:
df.head()
'''
About Dataset
Features description
date : the date of the game
time : the time of the game
comp : the competition of the game
round : the round of the game
day : the day of the week of the game
venue : the venue of the game
result : the result of the game
gf : the goals for the home team
ga : the goals for the away team
opponent: the opponent of the home team
xg : the expected goals for the home team
xga : the expected goals for the away team
poss : the possession of the home team
captain : the captain of the home team
formation : the formation of the home team
referee : the referee of the game
sh : the shots of the home team
sot : the shots on target of the home team
dist : the average distance of the shots of the home team
fk : the free kicks of the home team
pk : the penalty kicks of the home team
pka : the penalty kicks attempted of the home team
season : the season year of the match
team: the home team
'''

'\nAbout Dataset\nFeatures description\ndate : the date of the game\ntime : the time of the game\ncomp : the competition of the game\nround : the round of the game\nday : the day of the week of the game\nvenue : the venue of the game\nresult : the result of the game\ngf : the goals for the home team\nga : the goals for the away team\nopponent: the opponent of the home team\nxg : the expected goals for the home team\nxga : the expected goals for the away team\nposs : the possession of the home team\ncaptain : the captain of the home team\nformation : the formation of the home team\nreferee : the referee of the game\nsh : the shots of the home team\nsot : the shots on target of the home team\ndist : the average distance of the shots of the home team\nfk : the free kicks of the home team\npk : the penalty kicks of the home team\npka : the penalty kicks attempted of the home team\nseason : the season year of the match\nteam: the home team\n'

In [3]:
df.isnull().values.any()

np.False_

In [4]:
df.isnull().sum()

date            0
time            0
comp            0
round           0
day             0
venue           0
result          0
gf              0
ga              0
opponent        0
xg              0
xga             0
poss            0
captain         0
formation       0
referee         0
match report    0
sh              0
sot             0
fk              0
pk              0
pkatt           0
season          0
team            0
dtype: int64

In [5]:
df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,formation,referee,match report,sh,sot,fk,pk,pkatt,season,team
0,2020-09-21,20:15 (21:15),Premier League,Matchweek 2,Mon,Away,W,3,1,Wolves,...,4-2-3-1,Andre Marriner,Match Report,13,8,2,1,1,2024,Manchester City
1,2020-09-27,16:30 (17:30),Premier League,Matchweek 3,Sun,Home,L,2,5,Leicester City,...,4-2-3-1,Michael Oliver,Match Report,16,5,1,0,0,2024,Manchester City
2,2020-10-03,17:30 (18:30),Premier League,Matchweek 4,Sat,Away,D,1,1,Leeds United,...,4-3-3,Mike Dean,Match Report,23,1,1,0,0,2024,Manchester City
3,2020-10-17,17:30 (18:30),Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,...,3-1-4-2,Chris Kavanagh,Match Report,13,5,0,0,0,2024,Manchester City
4,2020-10-24,12:30 (13:30),Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,...,4-3-3,Anthony Taylor,Match Report,14,7,1,0,0,2024,Manchester City

In [6]:
df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'captain', 'formation', 'referee',
       'match report', 'sh', 'sot', 'fk', 'pk', 'pkatt', 'season', 'team'],
      dtype='object')

In [7]:
df.drop(["date","time","day","referee","captain","match report"], axis=1, inplace=True)

In [8]:
df.head()

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,Premier League,Matchweek 2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,Premier League,Matchweek 3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,Premier League,Matchweek 4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,Premier League,Matchweek 5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,Premier League,Matchweek 6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [9]:
df.isnull().sum()

comp         0
round        0
venue        0
result       0
gf           0
ga           0
opponent     0
xg           0
xga          0
poss         0
formation    0
sh           0
sot          0
fk           0
pk           0
pkatt        0
season       0
team         0
dtype: int64

In [10]:
df = df.dropna(axis=1, how='any')

In [11]:
df.head()

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,Premier League,Matchweek 2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,Premier League,Matchweek 3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,Premier League,Matchweek 4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,Premier League,Matchweek 5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,Premier League,Matchweek 6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [12]:
df.drop(["captain"], axis=1, inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_23824\1300948637.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["captain"], axis=1, inplace=True)

In [13]:
df.head()

,Unnamed: 0,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,0,Premier League,Matchweek 2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,2,Premier League,Matchweek 3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,4,Premier League,Matchweek 4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,5,Premier League,Matchweek 5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,7,Premier League,Matchweek 6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [12]:
df.dtypes

comp          object
round         object
venue         object
result        object
gf             int64
ga             int64
opponent      object
xg           float64
xga          float64
poss           int64
formation     object
sh             int64
sot            int64
fk             int64
pk             int64
pkatt          int64
season         int64
team          object
dtype: object

In [15]:
df.columns

Index(['Unnamed: 0', 'comp', 'round', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'formation', 'sh', 'sot', 'fk', 'pk',
       'pkatt', 'season', 'team'],
      dtype='object')

In [16]:
df.head()

,Unnamed: 0,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,0,Premier League,Matchweek 2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,2,Premier League,Matchweek 3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,4,Premier League,Matchweek 4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,5,Premier League,Matchweek 5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,7,Premier League,Matchweek 6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [17]:
df.drop(["Unnamed: 0"], axis=1, inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_23824\2202187451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["Unnamed: 0"], axis=1, inplace=True)

In [18]:
df.head()

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,Premier League,Matchweek 2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,Premier League,Matchweek 3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,Premier League,Matchweek 4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,Premier League,Matchweek 5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,Premier League,Matchweek 6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [11]:
print(df['round'].unique())

['Matchweek 2' 'Matchweek 3' 'Matchweek 4' 'Matchweek 5' 'Matchweek 6'
 'Matchweek 7' 'Matchweek 8' 'Matchweek 9' 'Matchweek 10' 'Matchweek 11'
 'Matchweek 12' 'Matchweek 13' 'Matchweek 14' 'Matchweek 15'
 'Matchweek 17' 'Matchweek 18' 'Matchweek 19' 'Matchweek 1' 'Matchweek 20'
 'Matchweek 21' 'Matchweek 22' 'Matchweek 23' 'Matchweek 24'
 'Matchweek 16' 'Matchweek 25' 'Matchweek 26' 'Matchweek 29'
 'Matchweek 27' 'Matchweek 33' 'Matchweek 28' 'Matchweek 30'
 'Matchweek 31' 'Matchweek 32' 'Matchweek 34' 'Matchweek 35'
 'Matchweek 36' 'Matchweek 37' 'Matchweek 38']

In [13]:
df['round'] = df['round'].str.replace('Matchweek ', '').astype(int)

# Verify the changes
print(df['round'])

0        2
1        3
2        4
3        5
4        6
        ..
4783    34
4784    35
4785    36
4786    37
4787    38
Name: round, Length: 4788, dtype: int64

In [13]:
print(df['round'].unique())

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18 19  1 20 21 22 23 24 16
 25 26 29 27 33 28 30 31 32 34 35 36 37 38]

In [14]:
df.head()

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,captain,formation,sh,sot,fk,pk,pkatt,season,team
0,Premier League,2,Away,W,3,1,Wolves,1.9,0.6,65,Fernandinho,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,Premier League,3,Home,L,2,5,Leicester City,0.9,2.9,72,Fernandinho,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,Premier League,4,Away,D,1,1,Leeds United,1.2,2.4,49,Kevin De Bruyne,4-3-3,23,1,1,0,0,2024,Manchester City
3,Premier League,5,Home,W,1,0,Arsenal,1.3,0.9,58,Raheem Sterling,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,Premier League,6,Away,D,1,1,West Ham,1.0,0.3,69,Raheem Sterling,4-3-3,14,7,1,0,0,2024,Manchester City

In [30]:
print(df['round'].iloc[[0, 3, 5]])

0    2
3    5
5    7
Name: round, dtype: int64

In [23]:
# Print rows from index 5 to 10
print(df['round'].iloc[5:11])

5      7
6      8
7      9
8     10
9     11
10    12
Name: round, dtype: int64

In [24]:
df.head(10)

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,Premier League,2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,Premier League,3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,Premier League,4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,Premier League,5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,Premier League,6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City
5,Premier League,7,Away,W,1,0,Sheffield Utd,1.6,0.5,65,4-3-3,16,8,2,0,0,2024,Manchester City
6,Premier League,8,Home,D,1,1,Liverpool,1.4,1.2,54,4-2-3-1,6,2,0,0,1,2024,Manchester City
7,Premier League,9,Away,L,0,2,Tottenham,1.4,0.7,66,4-3-3,22,5,0,0,0,2024,Manchester City
8,Premier League,10,Home,W,5,0,Burnley,1.7,0.5,68,4-2-3-1,19,6,0,0,0,2024,Manchester City
9,Premier League,11,Home,W,2,0,Fulham,2.9,0.3,69,4-2-3-1,14,4,0,1,1,2024,Manchester City

In [25]:
df["comp"].head(10)

0    Premier League
1    Premier League
2    Premier League
3    Premier League
4    Premier League
5    Premier League
6    Premier League
7    Premier League
8    Premier League
9    Premier League
Name: comp, dtype: object

In [14]:
df['comp'] = 1
print(df['comp'])

0       1
1       1
2       1
3       1
4       1
       ..
4783    1
4784    1
4785    1
4786    1
4787    1
Name: comp, Length: 4788, dtype: int64

In [27]:
df.head(7)

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,1,2,Away,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,1,3,Home,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,1,4,Away,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,1,5,Home,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,1,6,Away,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City
5,1,7,Away,W,1,0,Sheffield Utd,1.6,0.5,65,4-3-3,16,8,2,0,0,2024,Manchester City
6,1,8,Home,D,1,1,Liverpool,1.4,1.2,54,4-2-3-1,6,2,0,0,1,2024,Manchester City

In [15]:
df['venue'] = df['venue'].replace({'Home': 1, 'Away': 2})
print(df['venue'])

0       2
1       1
2       2
3       1
4       2
       ..
4783    2
4784    1
4785    2
4786    1
4787    2
Name: venue, Length: 4788, dtype: int64

C:\Users\admin\AppData\Local\Temp\ipykernel_13724\1092668110.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['venue'] = df['venue'].replace({'Home': 1, 'Away': 2})

In [16]:
df.head()

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,1,2,2,W,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,1,3,1,L,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,1,4,2,D,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,1,5,1,W,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,1,6,2,D,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [17]:
df['result'] = df['result'].replace({'W': 3 , 'D': 1 , 'L' : 0 })
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_13724\2470150796.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['result'] = df['result'].replace({'W': 3 , 'D': 1 , 'L' : 0 })

,comp,round,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,fk,pk,pkatt,season,team
0,1,2,2,3,3,1,Wolves,1.9,0.6,65,4-2-3-1,13,8,2,1,1,2024,Manchester City
1,1,3,1,0,2,5,Leicester City,0.9,2.9,72,4-2-3-1,16,5,1,0,0,2024,Manchester City
2,1,4,2,1,1,1,Leeds United,1.2,2.4,49,4-3-3,23,1,1,0,0,2024,Manchester City
3,1,5,1,3,1,0,Arsenal,1.3,0.9,58,3-1-4-2,13,5,0,0,0,2024,Manchester City
4,1,6,2,1,1,1,West Ham,1.0,0.3,69,4-3-3,14,7,1,0,0,2024,Manchester City

In [18]:
df.dtypes

comp           int64
round          int64
venue          int64
result         int64
gf             int64
ga             int64
opponent      object
xg           float64
xga          float64
poss           int64
formation     object
sh             int64
sot            int64
fk             int64
pk             int64
pkatt          int64
season         int64
team          object
dtype: object

In [19]:
df = pd.get_dummies(df, columns=['opponent', 'formation', 'team'], drop_first=True)

# Verify the transformation
print(df.head())
df.dtypes

   comp  round  venue  result  gf  ga   xg  xga  poss  sh  ...  \
0     1      2      2       3   3   1  1.9  0.6    65  13  ...
1     1      3      1       0   2   5  0.9  2.9    72  16  ...
2     1      4      2       1   1   1  1.2  2.4    49  23  ...
3     1      5      1       3   1   0  1.3  0.9    58  13  ...
4     1      6      2       1   1   1  1.0  0.3    69  14  ...

   team_Newcastle United  team_Norwich City  team_Nottingham Forest  \
0                  False              False                   False
1                  False              False                   False
2                  False              False                   False
3                  False              False                   False
4                  False              False                   False

   team_Sheffield United  team_Southampton  team_Tottenham Hotspur  \
0                  False             False                   False
1                  False             False                   False
2                  False             False                   False
3                  False             False                   False
4                  False             False                   False

   team_Watford  team_West Bromwich Albion  team_West Ham United  \
0         False                      False                 False
1         False                      False                 False
2         False                      False                 False
3         False                      False                 False
4         False                      False                 False

   team_Wolverhampton Wanderers
0                         False
1                         False
2                         False
3                         False
4                         False

[5 rows x 86 columns]

comp                            int64
round                           int64
venue                           int64
result                          int64
gf                              int64
                                ...
team_Tottenham Hotspur           bool
team_Watford                     bool
team_West Bromwich Albion        bool
team_West Ham United             bool
team_Wolverhampton Wanderers     bool
Length: 86, dtype: object

In [20]:
df.head()

,comp,round,venue,result,gf,ga,xg,xga,poss,sh,...,team_Newcastle United,team_Norwich City,team_Nottingham Forest,team_Sheffield United,team_Southampton,team_Tottenham Hotspur,team_Watford,team_West Bromwich Albion,team_West Ham United,team_Wolverhampton Wanderers
0,1,2,2,3,3,1,1.9,0.6,65,13,...,False,False,False,False,False,False,False,False,False,False
1,1,3,1,0,2,5,0.9,2.9,72,16,...,False,False,False,False,False,False,False,False,False,False
2,1,4,2,1,1,1,1.2,2.4,49,23,...,False,False,False,False,False,False,False,False,False,False
3,1,5,1,3,1,0,1.3,0.9,58,13,...,False,False,False,False,False,False,False,False,False,False
4,1,6,2,1,1,1,1.0,0.3,69,14,...,False,False,False,False,False,False,False,False,False,False

In [21]:
df.dtypes

comp                            int64
round                           int64
venue                           int64
result                          int64
gf                              int64
                                ...
team_Tottenham Hotspur           bool
team_Watford                     bool
team_West Bromwich Albion        bool
team_West Ham United             bool
team_Wolverhampton Wanderers     bool
Length: 86, dtype: object

In [22]:
df.to_csv("processed-premier-league.csv")

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pickle

# Assuming df is your DataFrame and 'result' is your target variable

# Split data into features (X) and target (Y)
X = df.drop(columns=['result'])
Y = df['result']

# Split into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, Y_train)

# Make predictions
Y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {accuracy}")

with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

Accuracy: 0.9926931106471816

In [24]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Example single row of data
new_data = {
    'comp': 1,
    'round': 3,
    'venue': 1,  # Assuming 'home' = 1 and 'away' = 2
    'gf': 2,
    'ga': 5,
    'opponent': 'Leicester City',
    'xg': 0.9,
    'xga': 2.9,
    'poss': 72,
    'formation': '4-2-3-1',
    'sh': 16,
    'sot': 5,
    'fk': 1,
    'pk': 0,
    'pkatt': 0,
    'season': 2024,
    'team': 'Manchester City'
}

# Convert new_data into a DataFrame
new_df = pd.DataFrame([new_data])

# Apply the same preprocessing steps as applied to the training data

# One-hot encode categorical features
new_df = pd.get_dummies(new_df, columns=['opponent', 'formation', 'team'], drop_first=True)

# Ensure all features used in training are present
# This requires that the columns in new_df match those used in training
# Get the columns used in training
train_columns = X.columns

# Reindex new_df to have the same columns as the training set
new_df = new_df.reindex(columns=train_columns, fill_value=0)

# Scaling features if scaling was applied
# Assuming you used StandardScaler for scaling
scaler = StandardScaler()
# Fit scaler on training data and transform the new data
new_df[['xg', 'xga', 'poss']] = scaler.fit_transform(new_df[['xg', 'xga', 'poss']])

# Predict using the trained model
prediction = model.predict(new_df)

print(f"Prediction for the new data row: {prediction[0]}")

Prediction for the new data row: 0